# Generated by Django 5.0.6 on 2024-06-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0002_remove_profile_phone_number_profile_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='blank_profile.jpg', upload_to='profilepic'),
        ),
    ]
